### ISSUE TITLE
Converts all symbols to layers on my page after export

### ISSUE THREAD

**Issue by gailrankin** [DWilliames/PDF-export-sketch-plugin#10]
I'm on the new version of Sketch and have been having lots of trouble with this plugin. First it was deleting entire "symbol-master artboards" so I no longer export those. But now, it's converting all my symbols to layers after I export. I go a bit crazy with symbols since I have loads of state changes so this is a HUGE inconvenience.

**Comment by DWilliames** [comment]
Sorry to hear @gailrankin — that would be a huge inconvenience. Thanks for bringing this to my attention. I will try and look into this as soon as I get a chance.

**Comment by Guruabyss** [comment]
I've also run across this too! I have to duplicate my file in Sketch 44.1 then export the artboards. Also in Sketch 45 it no longer created any file during PDF export.

**Comment by DWilliames** [comment]
Thanks @gailrankin and @Guruabyss. I just finished a rewrite! Let me know if the new version of the plugin doesn't seem to fix this issue and I will reopen it. Otherwise, in my testing it seems to have been fixed.

**Comment by Guruabyss** [comment]
Checked to see if the export fixed both the breaking of symbols and if it outputs a PDF. Looks like both issues have been fixed :) Thank you!!
