### ISSUE TITLE
Sketch 45

### ISSUE THREAD

**Issue by Guruabyss** [DWilliames/PDF-export-sketch-plugin#11]
Exporting artboards no longer generates a PDF file, no file is created.

**Comment by lauggh** [comment]
+1 Same issue

**Comment by DWilliames** [comment]
Thanks @Guruabyss.
A lot of stuff seems broken at the moment, I think I'm going to have to rethink the approach for how the exporting is done at the moment. 

Bare with me as I try to dig into it this weekend.

**Comment by DWilliames** [comment]
@Guruabyss @lauggh. This should be fixed now after a rewrite of the plugin. Let me know if you still experience any other issues. Thanks.
