### ISSUE TITLE
Ignore Prefix Broken 

### ISSUE THREAD

**Issue by corythorpe** [DWilliames/PDF-export-sketch-plugin#13]
The latest update broke the ignore prefix for me. It was working in the previous version.

**Comment by DWilliames** [comment]
Thanks for the heads up @Tasoli. Good catch.
Is this relating to the prefix based on the name of the artboards, or for the prefix on the page names?

**Comment by corythorpe** [comment]
This is relating to page names. I used the "-" character to denote pages I don't want exported to my PDF, and they still show up. I reverted to the previous version (which was still in my downloads folder) and it worked again.

**Comment by DWilliames** [comment]
Thanks @Tasoli. I have fixed this now. Please try it, and let me know if the fix isn't working for you.
