### ISSUE TITLE
Padd behaves differently when I have an icon on the left, compared to when it's on the right

### ISSUE THREAD

**Issue by sambazalo** [DWilliames/PDF-export-sketch-plugin#16]
As you can see in the screenshots, I can't get Paddy to behave the same on both of these symbols. 

The only difference in these symbols that I can figure out is that one has the icon on the left, one has it on the right.

The symbol with the icon on the right is behaving as expected.

I can't get the symbol with the icon on the left to do the same thing.

![screen shot 2018-04-19 at 1 01 56 pm](https://user-images.githubusercontent.com/29845358/38965737-892c8c22-43d2-11e8-896a-05375dc5ca49.png)

The layers are exactly the same.

![screen shot 2018-04-19 at 1 02 05 pm](https://user-images.githubusercontent.com/29845358/38965739-8959a9b4-43d2-11e8-85f9-80e8af836bfc.png)

And there are no constraints set in the symbol elements.

Any suggestions?

**Comment by DWilliames** [comment]
Hey @sambazalo. Sorry only just saw this. You accidentally submitted this issue on the wrong repository :P 

It might be too late now; but I'd suggest checking the alignment on your text label. It looks like you may have it centered or right aligned. In this case; ideally you'd have it left aligned in this case.

If you do still have issues, please submit another issue on the Paddy repo https://github.com/DWilliames/paddy-sketch-plugin. 👍
