### ISSUE TITLE
Using plugin with masked symbols

### ISSUE THREAD

**Issue by sambazalo** [DWilliames/PDF-export-sketch-plugin#17]
I am using masked symbols in my buttons to allow the button colour to be controlled with overrides. 

Is there a way I can get Paddy to work with this technique?

This is where I got stuck:

![screen shot 2018-04-19 at 1 37 04 pm](https://user-images.githubusercontent.com/29845358/38966586-1b013144-43d7-11e8-8453-1e5840338516.png)

![screen shot 2018-04-19 at 1 37 10 pm](https://user-images.githubusercontent.com/29845358/38966587-1b3f04d8-43d7-11e8-9d47-7f364161da6f.png)

**Comment by DWilliames** [comment]
Hey @sambazalo. Sorry, once again, wrong repo: https://github.com/DWilliames/paddy-sketch-plugin.
I'm not sure if Paddy will support this at the moment. But in my re-write of Paddy, which you can check out here https://github.com/DWilliames/paddy2-beta It will eventually work. 👍
