### ISSUE TITLE
Stopped working in Sketch Version 79 (133334)

### ISSUE THREAD

**Issue by dbraphael** [DWilliames/PDF-export-sketch-plugin#28]
I updated within the last day or so and the plugin is no longer working for me. No file is exported. No error is shown

**Comment by kxatzidakis** [comment]
Same here... :(

**Comment by CVSccorpus** [comment]
same here

**Comment by dbraphael** [comment]
We got this to work by deselecting the export as png checkbox. Does **NOT** work when the checkbox is selected.

**Comment by audiopizza** [comment]
The error when the Export as PNGs into PDF option is checked is "MSExportRequest.exportRequestFromExportFormat_layer_inRect_useIDForName is not a function".

**Comment by DWilliames** [comment]
Should finally be fixed now.
