### ISSUE TITLE
PDF export has stopped working

### ISSUE THREAD

**Issue by ccwriggs** [DWilliames/PDF-export-sketch-plugin#29]
It was working a couple of weeks ago but suddenly stopped.

I do not have the 'Export as PNG into PDF' selected which seems to have been the previous issue.

Any ideas?

**Comment by ccwriggs** [comment]
I managed to isolate the issue and it is broken when trying to export from Sketch version 82 or above....

**Comment by ccwriggs** [comment]
Only way to fix is go back to using V81.1 or below.

**Comment by DWilliames** [comment]
Should be fixed now.
