### ISSUE TITLE
PDF export pluginn for Sketch is broken on version 82 or above....

### ISSUE THREAD

**Issue by ccwriggs** [DWilliames/PDF-export-sketch-plugin#30]

**Comment by ccwriggs** [comment]
Only way to fix is go back to using V81.1 or below.

**Comment by jameskachan** [comment]
Same issue, the Plugin does not work, It seems to, but no PDFs actually output. This was broken by recent Sketch 82 updates.

This plugin is critical to my workflow. I would deeply appreciate it being updated. Please! ❤️

It is not possible to export selected artboards as PDFs.
A possible issue causing it may be that Sketch has listed that they recently made some changes to PDF outputs:

**Sketch 82** 
_"We’ve optimized the way fonts are embedded when exporting Artboards to PDF so the size of your exported PDF is smaller."_

https://www.sketch.com/updates/

**Comment by s-yongchul** [comment]
Same issue. Hopefully fix this issue as soon as possible. This plugin is very important for my team project.

**Comment by tb-jacob** [comment]
+1 really missing this plugin on v82!

**Comment by DWilliames** [comment]
Hey all — I'm really sorry that the plugin broke.
I'm not sure if I'm going to be able to fix it. I also currently don't have an active Sketch license to use to test any changes with.

A quick note as a potential work around...
If you export every Artboard individually as a PDF, after adding 'PDF' as an export preset, then using Sketch's "Export Current Selection... (CMD + E)"

Then to combine all the exported PDFs into a single one — select all the PDF files together in Finder, then right click and go 'Quick actions > Create PDF' that will combine them all into one and is pretty quick to do.

Hopefully that helps.

**Comment by zhixuans** [comment]
Same issue.

**Comment by mandraxg** [comment]
> Hey all — I'm really sorry that the plugin broke. I'm not sure if I'm going to be able to fix it. I also currently don't have an active Sketch license to use to test any changes with.
> 
> A quick note as a potential work around... If you export every Artboard individually as a PDF, after adding 'PDF' as an export preset, then using Sketch's "Export Current Selection... (CMD + E)"
> 
> Then to combine all the exported PDFs into a single one — select all the PDF files together in Finder, then right click and go 'Quick actions > Create PDF' that will combine them all into one and is pretty quick to do.
> 
> Hopefully that helps.

Hi David, i'm a user of your plugin for a long time. i'm very bored to see that your plugin doesn't work anymore. The native PDF export feature is uesless... I've sent a message to Sketch Support to express my dissatisfaction.

I will be happy to help you to find a fix :) Let me know what you need

**Comment by mandraxg** [comment]
Below the error log : 

`TypeError: MSPDFBookExporter.pdfFromArtboard is not a function. (In 'MSPDFBookExporter.pdfFromArtboard(artboard)', 'MSPDFBookExporter.pdfFromArtboard' is undefined)
    at /Users/XXX/Library/Application Support/com.bohemiancoding.sketch3/Plugins/PDF Export.sketchplugin/Contents/Sketch/main.js:546:58
    at forEach[native code] (/)
    at exportArtboards (/Users/XXX/Library/Application Support/com.bohemiancoding.sketch3/Plugins/PDF Export.sketchplugin/Contents/Sketch/main.js:519:20)
    at /Users/XXX/Library/Application Support/com.bohemiancoding.sketch3/Plugins/PDF Export.sketchplugin/Contents/Sketch/main.js:406:20
    at showOptionsWindow (/Users/XXX/Library/Application Support/com.bohemiancoding.sketch3/Plugins/PDF Export.sketchplugin/Contents/Sketch/main.js:336:13)
    at exportForOption (/Users/XXX/Library/Application Support/com.bohemiancoding.sketch3/Plugins/PDF Export.sketchplugin/Contents/Sketch/main.js:395:20)
    at exportSelection (/Users/XXX/Library/Application Support/com.bohemiancoding.sketch3/Plugins/PDF Export.sketchplugin/Contents/Sketch/main.js:376:18)
`

**Comment by lonjame** [comment]
+1 would love to see the plugin in Sketch 82

**Comment by DWilliames** [comment]
Alright everyone — I downloaded the latest version of Sketch and signed up for a new 30 days trial to dig into this.
After a bunch of hours, I think I cracked it!! 😅

Can you please download the latest version and try now and see if it works again for you.

**Comment by lonjame** [comment]
Thank you so much. That was fast :) It works!!!! 🥇 I´m using Sketch Version 82.1 (137007)

**Comment by zhixuans** [comment]
> Alright everyone — I downloaded the latest version of Sketch and signed up for a new 30 days trial to dig into this. After a bunch of hours, I think I cracked it!! 😅
> 
> Can you please download the latest version and try now and see if it works again for you.

thank~

**Comment by mandraxg** [comment]
Thanks a lot Dave. The fix looks good :)

**Comment by ccwriggs** [comment]
DWilliams I know it's not much but I shouted you a coffee for taking the time to resolve this for everyone. Much appreciated!

I urge others on the thread to do the same to show your appreciation. See the link at the bottom of the screen of the < Code > tab above 👍 

![image](https://user-images.githubusercontent.com/98323060/151539806-aa7a7b46-4231-4cee-95b9-8a27d906f5b5.png)

**Comment by mandraxg** [comment]
The Paypal link : https://www.paypal.me/dtw/5

**Comment by mandraxg** [comment]
[Shout him a coffee](https://www.paypal.me/dtw/5) ☕️

**Comment by jameskachan** [comment]
Thank you! - Yes, Shout this good man a coffee please!

ver 2.2 does seem to work, I just manually installed it from Github.

@DWilliames, would it be possible to push this update so that Sketch Runner can pick it up, and Sketch itself can alert that there is a plugin update available?

<img width="372" alt="Screen Shot 2022-01-28 at 11 30 27 AM" src="https://user-images.githubusercontent.com/5762476/151585017-7550546f-63b9-41c3-97a1-aba5bfe9ad5a.png">

**Comment by tb-jacob** [comment]
Big thanks @DWilliames and shouted!
