### ISSUE TITLE
Issue editing elements after exporting PDF

### ISSUE THREAD

**Issue by rtkramer** [DWilliames/PDF-export-sketch-plugin#5]
Seems to be an issue with Sketch Elements displaying weird editing behavior after exporting a PDF file using this tool.

Sketch Version 43.2
Steps to reproduce
1. Install the plugin.
2. Choose an artboard in Sketch and export to PDF using the plugin.
3. After export return to the Sketch artboard and select a text element and hit return to edit the text.
4. Text element cannot be changed but shows new text on top of old text.
5. Quitting Sketch and opening the file again or drawing a new artboard then deleting it seems to resolve it.

![bitmap](https://cloud.githubusercontent.com/assets/15931910/25548231/48d4d0a0-2c20-11e7-8c2f-3c4f62f78b69.png)

**Comment by DWilliames** [comment]
Thanks @rtkramer. Sorry for the late reply. This is really weird behaviour — I spent a while digging into this a couple of months ago, and couldn't find a solution.
I'll try to look into it further when I get a chance... thanks for your patience.

**Comment by DWilliames** [comment]
@rtkramer, I just finished rewriting the plugin to take a different approach in how it does the exporting.
From my testing, it seems to have fixed this behaviour. If for some reason you see this behaviour again, please let me know.
