### ISSUE TITLE
Auto Layout vertical centering is ignored on PDF export

### ISSUE THREAD

**Issue by r-carlander** [DWilliames/PDF-export-sketch-plugin#6]
First of all, thank you for an awesome plugin! :)

However, i found a bug. When using [Auto Layout](https://animaapp.github.io/) to vertically center text in a symbol with text overrides, the PDF export ignores the vertical centering. You can see an example of this as well as the specific Auto Layout setting in question here: 

<a href="https://ibb.co/fspCca"><img src="https://thumb.ibb.co/fspCca/Sk_rmbillede_2017_05_31_kl_16_11_33.png" alt="Sk_rmbillede_2017_05_31_kl_16_11_33" border="0"></a>&nbsp;&nbsp;&nbsp;<a href="https://ibb.co/ipmKOF"><img src="https://thumb.ibb.co/ipmKOF/Sk_rmbillede_2017_05_31_kl_16_09_12.png" alt="Sk_rmbillede_2017_05_31_kl_16_09_12" border="0"></a>

Sketch version: 44.1

Steps to reproduce:

1. Create a rectangle on an empty artboard
2. Place one line of text on top of the rectangle
3. Make the textfield and the rectangle into a symbol
4. Go into the symbol, click on the text layer and select "Pin to center vertically" in the Auto Layout pane.
4. Go back to the artboard and duplicate the symbol a couple of times and use text overrides to make one of the copied symbols text layer long enough to split into two lines of text
5. Do a PDF-export and you should end up with a PDF that ignores the vertical centering, rendering the symbol with two lines of text looking weird because the two lines start from the middle and down instead of being centered vertically

I have included the exported PDF and the Sketch file as well:
https://adobe.ly/2qAzlfu

**Comment by DWilliames** [comment]
Sorry for the late reply, thanks for this @r-carlander, I really appreciate the detailed bug report.
I haven't personally tested with the Auto Layout plugin — so I'll definitely look into this when I get a chance.

**Comment by DWilliames** [comment]
Hi @r-carlander, I just finished a rewrite of the plugin. In my tests this issue appears to now be fixed. If it seems to still occur please let me know and I will reopen the this issue. Thanks again.

**Comment by r-carlander** [comment]
Thanks a lot, @DWilliames! It's working now 👍
