### ISSUE TITLE
Symbol positioning off after exporting to pdf

### ISSUE THREAD

**Issue by CVSccorpus** [DWilliames/PDF-export-sketch-plugin#8]
after exporting for pdf, it looks like some of the symbols i use reposition themselves, as well as change the copy to something it was previously

Correct positioning
![screen shot 2017-06-06 at 11 26 25 am](https://user-images.githubusercontent.com/27236603/26837266-06a0166e-4aab-11e7-85f4-6715872a6b94.png)

after export
![screen shot 2017-06-06 at 11 22 41 am](https://user-images.githubusercontent.com/27236603/26837147-ac188e56-4aaa-11e7-8d44-8abf99f28d72.png)

**Comment by DWilliames** [comment]
That is a really weird behaviour, thanks for letting me know @CVSccorpus. The plugin is built upon Sketch's in-build PDF export, so it's weird that it would produce such different results.
I will look into this when I get a chance.

**Comment by DWilliames** [comment]
Hey @CVSccorpus, I just finished a rewrite of the plugin — and I think the new approach fixes this issue that you found. If you do find that with the latest version of the plugin you are still getting this weird behaviour, let me know and I will reopen this issues. Thanks :)
